spring.application.name=trainer-workload
server.port=8081

# MongoDB
spring.data.mongodb.uri=mongodb://mongo-db:27017/trainer_workload_db
spring.data.mongodb.database=trainer_workload_db

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ActiveMQ
spring.activemq.broker-url=tcp://activemq:61616
spring.activemq.user=admin
spring.activemq.password=admin

# Logging
logging.level.root=INFO
